#!/bin/bash
sudo apt update
apt list --upgradable
read -p "Continue to upgrade? [Y/n] " cont

if [ $cont == 'y' ] || [ $cont == 'Y' ]
then
    sudo apt upgrade -y && sudo apt autoremove
else
    echo Cancelled
fi
